services:
  backend:
    environment:
      - ENV=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    command: npm run dev -- --host 0.0.0.0
    # command: ["sh", "-lc", "tail -f /dev/null"]
