services:
  backend:
    environment:
      - ENV=production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4

  frontend:
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8000
    command: npm run build
